// Autogenerated with DRAKON Editor 1.31



    void Начало() {
        // item 18
        //Вводим массив данных которые будут отсортированны
        int[] arr ={4,6,8,4,2};
        int j=0;
        int VstavkaVRazriv=0;
        int MestoRazriva=0;
        foreach (int i in arr) {
            // item 770001
            j=i-1;
            while (true) {
                // item 770002
                if (j=!0) {
                    
                } else {
                    break;
                }
                // item 61
                if ((if(arr[j]>=arr[i])) && (!(if(arr[j-1]>=arr[i])))) {
                    // item 66
                    //Массив не отсортирован
                    VstavkaVRazriv=i;
                    MestoRazriva=j;
                    // item 195
                    Перемещение
                } else {
                    
                }
                // item 770003
                j--;
            }
        }
        // item 17
        //Отсортированный массив
    }

    void Перемещение(/*Вход, arr[], VstavkaVRazriv, MestoRazriva, Выход, arr[]*/) {
        // item 120
        /*arr[]
        VstavkaVRazriv
        MestoRazriva*/
        // item 100
        String newarr=null;
        foreach (int i in arr) {
            // item 1030001
            if (switch == i=MestoRazriv;) {
                // item 113
                newarr=+(Convert.ToString(arr[VstavkaVRazriv]))+" "+(Convert.ToString(arr[i]));
            } else {
                // item 1030002
                if (switch == i=VstavkaVRazriv;) {
                    
                } else {
                    // item 1030003
                    if (switch == default) {
                        
                    } else {
                        // item 1030004
                        throw new InvalidOperationException("Not expected:  " + switch.ToString());
                    }
                    // item 102
                    newarr=+(Convert.ToString(arr[i]))+" ";
                }
            }
        }
        // item 196
        Переработка
        // item 122
        //newarr[]
    }

    void Переработка(Здесь из строки с числами, через пробел, мы сделаем массив) {
        // item 157
        int RazmArr=0;
        string Buffer=Null;
        // item 137
        Строка с элементами массива, 
        в нашем случае это 
        
        newarr
        foreach (int i in (newarr.ToStringArray)) {
            // item 144
            if (if(newarr[i]=Char.IsWhiteSpace)) {
                // item 148
                RzmArr++;
            } else {
                
            }
        }
        // item 159
        RazmArr--;
        new Arr[RazmArr];
        j=0;
        i=0;
        foreach (int i in (newarr.ToStringArray)) {
            // item 173
            if (if(newarr[i]=Char.IsNumber)) {
                // item 162
                Buffer=+newarr[i];
            } else {
                // item 172
                Arr[j]=(Convert.ToInt32(Buffer));
                j++;
                Buffer=Null;
            }
        }
        // item 178
        //Arr[]
    }

